### ISSUE TITLE
Script doesn't parse date from website

### ISSUE THREAD

**Issue by johnjohndoe** [wo-ist-markt/wo-ist-markt-berlin-update-reminder#3]
The script seems to be broken. I don't understand why. Here is the tail of raw log of [this Travis build](https://travis-ci.org/wo-ist-markt/wo-ist-markt-berlin-update-reminder/builds/591096537).

``` bash
travis_time:start:07f735d7
[0K$ bash update_reminder.sh
Dates don't match!
daten.berlin.de: 03.05.2019
wo-ist-markt.de: 
travis_time:end:07f735d7:start=1569776346008707586,finish=1569776347412036133,duration=1403328547,event=script
[0K[31;1mThe command "bash update_reminder.sh" exited with 1.[0m

Done. Your build exited with 1.
```

/cc @NWuensche @k-nut

**Comment by k-nut** [comment]
@johnjohndoe I'd assume that this was a temporary problem. I retriggered the build and at that time it worked. I also created #4 that fixes a mixup in the output though. Let me know what you think.

**Comment by johnjohndoe** [comment]
@k-nut Thanks again. This issue went out of sight for me.
